package com.til.dusk.common.register.multiblock.multiblocks;

import com.til.dusk.common.config.ConfigField;
import com.til.dusk.common.register.mana_level.mana_level.ManaLevel;
import com.til.dusk.common.register.multiblock.DefaultBlockPack;
import com.til.dusk.common.register.multiblock.IMultiBlockPack;
import com.til.dusk.common.register.multiblock.LevelMultiBlock;
import com.til.dusk.common.register.ore.block.OreBlock;
import com.til.dusk.util.BlockStateUtil;
import net.minecraft.core.BlockPos;
import net.minecraft.resources.ResourceLocation;
import net.minecraftforge.registries.ForgeRegistries;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * @author til
 */
public class MK1MultiBlock extends LevelMultiBlock {

    public MK1MultiBlock() {
        super("mk1");
    }


    @Override
    public List<DefaultBlockPack> asDefaultBlockPack(ManaLevel manaLevel) {
        List<DefaultBlockPack> list = new ArrayList<>(blockPacks.size());
        for (IMultiBlockPack<ManaLevel> blockPack : blockPacks) {
            list.add(blockPack.ofDefaultBlockPack(manaLevel));
        }
        return list;
    }

    @Override
    public List<IMultiBlockPack<ManaLevel>> getMultiBlockPack(ManaLevel manaLevel) {
        return blockPacks;
    }

    @ConfigField
    public List<IMultiBlockPack<ManaLevel>> blockPacks = List.of();

    @Override
    public void defaultConfig() {
        blockPacks = List.of(
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.coil.name, null)
                        .addPos(new BlockPos(-8, -1, -2))
                        .addPos(new BlockPos(-8, -1, 2))
                        .addPos(new BlockPos(-7, -1, -3))
                        .addPos(new BlockPos(-7, -1, -2))
                        .addPos(new BlockPos(-7, -1, 2))
                        .addPos(new BlockPos(-7, -1, 3))
                        .addPos(new BlockPos(-3, -1, -7))
                        .addPos(new BlockPos(-3, -1, 7))
                        .addPos(new BlockPos(-2, -1, -8))
                        .addPos(new BlockPos(-2, -1, -7))
                        .addPos(new BlockPos(-2, -1, 7))
                        .addPos(new BlockPos(-2, -1, 8))
                        .addPos(new BlockPos(2, -1, -8))
                        .addPos(new BlockPos(2, -1, -7))
                        .addPos(new BlockPos(2, -1, 7))
                        .addPos(new BlockPos(2, -1, 8))
                        .addPos(new BlockPos(3, -1, -7))
                        .addPos(new BlockPos(3, -1, 7))
                        .addPos(new BlockPos(7, -1, -3))
                        .addPos(new BlockPos(7, -1, -2))
                        .addPos(new BlockPos(7, -1, 2))
                        .addPos(new BlockPos(7, -1, 3))
                        .addPos(new BlockPos(8, -1, -2))
                        .addPos(new BlockPos(8, -1, 2))
                        .addPos(new BlockPos(-9, 0, -2))
                        .addPos(new BlockPos(-9, 0, 2))
                        .addPos(new BlockPos(-8, 0, -3))
                        .addPos(new BlockPos(-8, 0, 3))
                        .addPos(new BlockPos(-6, 0, -3))
                        .addPos(new BlockPos(-6, 0, -2))
                        .addPos(new BlockPos(-6, 0, 2))
                        .addPos(new BlockPos(-6, 0, 3))
                        .addPos(new BlockPos(-3, 0, -8))
                        .addPos(new BlockPos(-3, 0, -6))
                        .addPos(new BlockPos(-3, 0, 6))
                        .addPos(new BlockPos(-3, 0, 8))
                        .addPos(new BlockPos(-2, 0, -9))
                        .addPos(new BlockPos(-2, 0, -6))
                        .addPos(new BlockPos(-2, 0, 6))
                        .addPos(new BlockPos(-2, 0, 9))
                        .addPos(new BlockPos(2, 0, -9))
                        .addPos(new BlockPos(2, 0, -6))
                        .addPos(new BlockPos(2, 0, 6))
                        .addPos(new BlockPos(2, 0, 9))
                        .addPos(new BlockPos(3, 0, -8))
                        .addPos(new BlockPos(3, 0, -6))
                        .addPos(new BlockPos(3, 0, 6))
                        .addPos(new BlockPos(3, 0, 8))
                        .addPos(new BlockPos(6, 0, -3))
                        .addPos(new BlockPos(6, 0, -2))
                        .addPos(new BlockPos(6, 0, 2))
                        .addPos(new BlockPos(6, 0, 3))
                        .addPos(new BlockPos(8, 0, -3))
                        .addPos(new BlockPos(8, 0, 3))
                        .addPos(new BlockPos(9, 0, -2))
                        .addPos(new BlockPos(9, 0, 2))
                        .addPos(new BlockPos(-8, 1, -2))
                        .addPos(new BlockPos(-8, 1, 2))
                        .addPos(new BlockPos(-7, 1, -3))
                        .addPos(new BlockPos(-7, 1, -2))
                        .addPos(new BlockPos(-7, 1, 2))
                        .addPos(new BlockPos(-7, 1, 3))
                        .addPos(new BlockPos(-3, 1, -7))
                        .addPos(new BlockPos(-3, 1, 7))
                        .addPos(new BlockPos(-2, 1, -8))
                        .addPos(new BlockPos(-2, 1, -7))
                        .addPos(new BlockPos(-2, 1, 7))
                        .addPos(new BlockPos(-2, 1, 8))
                        .addPos(new BlockPos(2, 1, -8))
                        .addPos(new BlockPos(2, 1, -7))
                        .addPos(new BlockPos(2, 1, 7))
                        .addPos(new BlockPos(2, 1, 8))
                        .addPos(new BlockPos(3, 1, -7))
                        .addPos(new BlockPos(3, 1, 7))
                        .addPos(new BlockPos(7, 1, -3))
                        .addPos(new BlockPos(7, 1, -2))
                        .addPos(new BlockPos(7, 1, 2))
                        .addPos(new BlockPos(7, 1, 3))
                        .addPos(new BlockPos(8, 1, -2))
                        .addPos(new BlockPos(8, 1, 2)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.substitution.name, null)
                        .addPos(new BlockPos(-8, -1, -1))
                        .addPos(new BlockPos(-8, -1, 0))
                        .addPos(new BlockPos(-8, -1, 1))
                        .addPos(new BlockPos(-1, -1, -8))
                        .addPos(new BlockPos(-1, -1, 8))
                        .addPos(new BlockPos(0, -1, -8))
                        .addPos(new BlockPos(0, -1, 0))
                        .addPos(new BlockPos(0, -1, 8))
                        .addPos(new BlockPos(1, -1, -8))
                        .addPos(new BlockPos(1, -1, 8))
                        .addPos(new BlockPos(8, -1, -1))
                        .addPos(new BlockPos(8, -1, 0))
                        .addPos(new BlockPos(8, -1, 1))
                        .addPos(new BlockPos(-9, 0, -1))
                        .addPos(new BlockPos(-9, 0, 0))
                        .addPos(new BlockPos(-9, 0, 1))
                        .addPos(new BlockPos(-7, 0, -1))
                        .addPos(new BlockPos(-7, 0, 0))
                        .addPos(new BlockPos(-7, 0, 1))
                        .addPos(new BlockPos(-1, 0, -9))
                        .addPos(new BlockPos(-1, 0, -7))
                        .addPos(new BlockPos(-1, 0, 7))
                        .addPos(new BlockPos(-1, 0, 9))
                        .addPos(new BlockPos(0, 0, -9))
                        .addPos(new BlockPos(0, 0, -7))
                        .addPos(new BlockPos(0, 0, 7))
                        .addPos(new BlockPos(0, 0, 9))
                        .addPos(new BlockPos(1, 0, -9))
                        .addPos(new BlockPos(1, 0, -7))
                        .addPos(new BlockPos(1, 0, 7))
                        .addPos(new BlockPos(1, 0, 9))
                        .addPos(new BlockPos(7, 0, -1))
                        .addPos(new BlockPos(7, 0, 0))
                        .addPos(new BlockPos(7, 0, 1))
                        .addPos(new BlockPos(9, 0, -1))
                        .addPos(new BlockPos(9, 0, 0))
                        .addPos(new BlockPos(9, 0, 1))
                        .addPos(new BlockPos(-8, 1, -1))
                        .addPos(new BlockPos(-8, 1, 0))
                        .addPos(new BlockPos(-8, 1, 1))
                        .addPos(new BlockPos(-1, 1, -8))
                        .addPos(new BlockPos(-1, 1, 8))
                        .addPos(new BlockPos(0, 1, -8))
                        .addPos(new BlockPos(0, 1, 0))
                        .addPos(new BlockPos(0, 1, 8))
                        .addPos(new BlockPos(1, 1, -8))
                        .addPos(new BlockPos(1, 1, 8))
                        .addPos(new BlockPos(8, 1, -1))
                        .addPos(new BlockPos(8, 1, 0))
                        .addPos(new BlockPos(8, 1, 1)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.partialPressure.name, null)
                        .addPos(new BlockPos(-7, -1, -5))
                        .addPos(new BlockPos(-7, -1, -4))
                        .addPos(new BlockPos(-7, -1, 4))
                        .addPos(new BlockPos(-7, -1, 5))
                        .addPos(new BlockPos(-6, -1, -6))
                        .addPos(new BlockPos(-6, -1, -5))
                        .addPos(new BlockPos(-6, -1, 5))
                        .addPos(new BlockPos(-6, -1, 6))
                        .addPos(new BlockPos(-5, -1, -7))
                        .addPos(new BlockPos(-5, -1, -6))
                        .addPos(new BlockPos(-5, -1, 6))
                        .addPos(new BlockPos(-5, -1, 7))
                        .addPos(new BlockPos(-4, -1, -7))
                        .addPos(new BlockPos(-4, -1, 7))
                        .addPos(new BlockPos(4, -1, -7))
                        .addPos(new BlockPos(4, -1, 7))
                        .addPos(new BlockPos(5, -1, -7))
                        .addPos(new BlockPos(5, -1, -6))
                        .addPos(new BlockPos(5, -1, 6))
                        .addPos(new BlockPos(5, -1, 7))
                        .addPos(new BlockPos(6, -1, -6))
                        .addPos(new BlockPos(6, -1, -5))
                        .addPos(new BlockPos(6, -1, 5))
                        .addPos(new BlockPos(6, -1, 6))
                        .addPos(new BlockPos(7, -1, -5))
                        .addPos(new BlockPos(7, -1, -4))
                        .addPos(new BlockPos(7, -1, 4))
                        .addPos(new BlockPos(7, -1, 5))
                        .addPos(new BlockPos(-8, 0, -5))
                        .addPos(new BlockPos(-8, 0, -4))
                        .addPos(new BlockPos(-8, 0, 4))
                        .addPos(new BlockPos(-8, 0, 5))
                        .addPos(new BlockPos(-7, 0, -6))
                        .addPos(new BlockPos(-7, 0, 6))
                        .addPos(new BlockPos(-6, 0, -7))
                        .addPos(new BlockPos(-6, 0, -4))
                        .addPos(new BlockPos(-6, 0, 4))
                        .addPos(new BlockPos(-6, 0, 7))
                        .addPos(new BlockPos(-5, 0, -8))
                        .addPos(new BlockPos(-5, 0, -5))
                        .addPos(new BlockPos(-5, 0, 5))
                        .addPos(new BlockPos(-5, 0, 8))
                        .addPos(new BlockPos(-4, 0, -8))
                        .addPos(new BlockPos(-4, 0, -6))
                        .addPos(new BlockPos(-4, 0, 6))
                        .addPos(new BlockPos(-4, 0, 8))
                        .addPos(new BlockPos(4, 0, -8))
                        .addPos(new BlockPos(4, 0, -6))
                        .addPos(new BlockPos(4, 0, 6))
                        .addPos(new BlockPos(4, 0, 8))
                        .addPos(new BlockPos(5, 0, -8))
                        .addPos(new BlockPos(5, 0, -5))
                        .addPos(new BlockPos(5, 0, 5))
                        .addPos(new BlockPos(5, 0, 8))
                        .addPos(new BlockPos(6, 0, -7))
                        .addPos(new BlockPos(6, 0, -4))
                        .addPos(new BlockPos(6, 0, 4))
                        .addPos(new BlockPos(6, 0, 7))
                        .addPos(new BlockPos(7, 0, -6))
                        .addPos(new BlockPos(7, 0, 6))
                        .addPos(new BlockPos(8, 0, -5))
                        .addPos(new BlockPos(8, 0, -4))
                        .addPos(new BlockPos(8, 0, 4))
                        .addPos(new BlockPos(8, 0, 5))
                        .addPos(new BlockPos(-7, 1, -5))
                        .addPos(new BlockPos(-7, 1, -4))
                        .addPos(new BlockPos(-7, 1, 4))
                        .addPos(new BlockPos(-7, 1, 5))
                        .addPos(new BlockPos(-6, 1, -6))
                        .addPos(new BlockPos(-6, 1, -5))
                        .addPos(new BlockPos(-6, 1, 5))
                        .addPos(new BlockPos(-6, 1, 6))
                        .addPos(new BlockPos(-5, 1, -7))
                        .addPos(new BlockPos(-5, 1, -6))
                        .addPos(new BlockPos(-5, 1, 6))
                        .addPos(new BlockPos(-5, 1, 7))
                        .addPos(new BlockPos(-4, 1, -7))
                        .addPos(new BlockPos(-4, 1, 7))
                        .addPos(new BlockPos(4, 1, -7))
                        .addPos(new BlockPos(4, 1, 7))
                        .addPos(new BlockPos(5, 1, -7))
                        .addPos(new BlockPos(5, 1, -6))
                        .addPos(new BlockPos(5, 1, 6))
                        .addPos(new BlockPos(5, 1, 7))
                        .addPos(new BlockPos(6, 1, -6))
                        .addPos(new BlockPos(6, 1, -5))
                        .addPos(new BlockPos(6, 1, 5))
                        .addPos(new BlockPos(6, 1, 6))
                        .addPos(new BlockPos(7, 1, -5))
                        .addPos(new BlockPos(7, 1, -4))
                        .addPos(new BlockPos(7, 1, 4))
                        .addPos(new BlockPos(7, 1, 5)),
                new IMultiBlockPack.BlockStateBlockPack<ManaLevel>(() -> BlockStateUtil.create(ForgeRegistries.BLOCKS.getValue(new ResourceLocation("minecraft:glowstone")), (Map<String, String>) null))
                        .addPos(new BlockPos(-9, 0, -3))
                        .addPos(new BlockPos(-9, 0, 3))
                        .addPos(new BlockPos(-8, 0, -6))
                        .addPos(new BlockPos(-8, 0, 6))
                        .addPos(new BlockPos(-7, 0, -7))
                        .addPos(new BlockPos(-7, 0, 7))
                        .addPos(new BlockPos(-6, 0, -8))
                        .addPos(new BlockPos(-6, 0, -1))
                        .addPos(new BlockPos(-6, 0, 1))
                        .addPos(new BlockPos(-6, 0, 8))
                        .addPos(new BlockPos(-5, 0, -4))
                        .addPos(new BlockPos(-5, 0, 4))
                        .addPos(new BlockPos(-4, 0, -5))
                        .addPos(new BlockPos(-4, 0, 5))
                        .addPos(new BlockPos(-3, 0, -9))
                        .addPos(new BlockPos(-3, 0, 9))
                        .addPos(new BlockPos(-1, 0, -6))
                        .addPos(new BlockPos(-1, 0, 6))
                        .addPos(new BlockPos(1, 0, -6))
                        .addPos(new BlockPos(1, 0, 6))
                        .addPos(new BlockPos(3, 0, -9))
                        .addPos(new BlockPos(3, 0, 9))
                        .addPos(new BlockPos(4, 0, -5))
                        .addPos(new BlockPos(4, 0, 5))
                        .addPos(new BlockPos(5, 0, -4))
                        .addPos(new BlockPos(5, 0, 4))
                        .addPos(new BlockPos(6, 0, -8))
                        .addPos(new BlockPos(6, 0, -1))
                        .addPos(new BlockPos(6, 0, 1))
                        .addPos(new BlockPos(6, 0, 8))
                        .addPos(new BlockPos(7, 0, -7))
                        .addPos(new BlockPos(7, 0, 7))
                        .addPos(new BlockPos(8, 0, -6))
                        .addPos(new BlockPos(8, 0, 6))
                        .addPos(new BlockPos(9, 0, -3))
                        .addPos(new BlockPos(9, 0, 3)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.shackles.name, null)
                        .addPos(new BlockPos(-8, 0, -2))
                        .addPos(new BlockPos(-8, 0, -1))
                        .addPos(new BlockPos(-8, 0, 0))
                        .addPos(new BlockPos(-8, 0, 1))
                        .addPos(new BlockPos(-8, 0, 2))
                        .addPos(new BlockPos(-7, 0, -5))
                        .addPos(new BlockPos(-7, 0, -4))
                        .addPos(new BlockPos(-7, 0, -3))
                        .addPos(new BlockPos(-7, 0, -2))
                        .addPos(new BlockPos(-7, 0, 2))
                        .addPos(new BlockPos(-7, 0, 3))
                        .addPos(new BlockPos(-7, 0, 4))
                        .addPos(new BlockPos(-7, 0, 5))
                        .addPos(new BlockPos(-6, 0, -6))
                        .addPos(new BlockPos(-6, 0, -5))
                        .addPos(new BlockPos(-6, 0, 5))
                        .addPos(new BlockPos(-6, 0, 6))
                        .addPos(new BlockPos(-5, 0, -7))
                        .addPos(new BlockPos(-5, 0, -6))
                        .addPos(new BlockPos(-5, 0, 6))
                        .addPos(new BlockPos(-5, 0, 7))
                        .addPos(new BlockPos(-4, 0, -7))
                        .addPos(new BlockPos(-4, 0, 7))
                        .addPos(new BlockPos(-3, 0, -7))
                        .addPos(new BlockPos(-3, 0, 7))
                        .addPos(new BlockPos(-2, 0, -8))
                        .addPos(new BlockPos(-2, 0, -7))
                        .addPos(new BlockPos(-2, 0, 7))
                        .addPos(new BlockPos(-2, 0, 8))
                        .addPos(new BlockPos(-1, 0, -8))
                        .addPos(new BlockPos(-1, 0, 8))
                        .addPos(new BlockPos(0, 0, -8))
                        .addPos(new BlockPos(0, 0, 8))
                        .addPos(new BlockPos(1, 0, -8))
                        .addPos(new BlockPos(1, 0, 8))
                        .addPos(new BlockPos(2, 0, -8))
                        .addPos(new BlockPos(2, 0, -7))
                        .addPos(new BlockPos(2, 0, 7))
                        .addPos(new BlockPos(2, 0, 8))
                        .addPos(new BlockPos(3, 0, -7))
                        .addPos(new BlockPos(3, 0, 7))
                        .addPos(new BlockPos(4, 0, -7))
                        .addPos(new BlockPos(4, 0, 7))
                        .addPos(new BlockPos(5, 0, -7))
                        .addPos(new BlockPos(5, 0, -6))
                        .addPos(new BlockPos(5, 0, 6))
                        .addPos(new BlockPos(5, 0, 7))
                        .addPos(new BlockPos(6, 0, -6))
                        .addPos(new BlockPos(6, 0, -5))
                        .addPos(new BlockPos(6, 0, 5))
                        .addPos(new BlockPos(6, 0, 6))
                        .addPos(new BlockPos(7, 0, -5))
                        .addPos(new BlockPos(7, 0, -4))
                        .addPos(new BlockPos(7, 0, -3))
                        .addPos(new BlockPos(7, 0, -2))
                        .addPos(new BlockPos(7, 0, 2))
                        .addPos(new BlockPos(7, 0, 3))
                        .addPos(new BlockPos(7, 0, 4))
                        .addPos(new BlockPos(7, 0, 5))
                        .addPos(new BlockPos(8, 0, -2))
                        .addPos(new BlockPos(8, 0, -1))
                        .addPos(new BlockPos(8, 0, 0))
                        .addPos(new BlockPos(8, 0, 1))
                        .addPos(new BlockPos(8, 0, 2)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.slab.name, Map.of("half", "true", "waterlogged", "false", "facing", "up"))
                        .addPos(new BlockPos(-8, -2, -2))
                        .addPos(new BlockPos(-8, -2, -1))
                        .addPos(new BlockPos(-8, -2, 0))
                        .addPos(new BlockPos(-8, -2, 1))
                        .addPos(new BlockPos(-8, -2, 2))
                        .addPos(new BlockPos(-7, -2, -5))
                        .addPos(new BlockPos(-7, -2, -4))
                        .addPos(new BlockPos(-7, -2, -3))
                        .addPos(new BlockPos(-7, -2, -2))
                        .addPos(new BlockPos(-7, -2, 2))
                        .addPos(new BlockPos(-7, -2, 3))
                        .addPos(new BlockPos(-7, -2, 4))
                        .addPos(new BlockPos(-7, -2, 5))
                        .addPos(new BlockPos(-6, -2, -6))
                        .addPos(new BlockPos(-6, -2, -5))
                        .addPos(new BlockPos(-6, -2, 5))
                        .addPos(new BlockPos(-6, -2, 6))
                        .addPos(new BlockPos(-5, -2, -7))
                        .addPos(new BlockPos(-5, -2, -6))
                        .addPos(new BlockPos(-5, -2, 6))
                        .addPos(new BlockPos(-5, -2, 7))
                        .addPos(new BlockPos(-4, -2, -7))
                        .addPos(new BlockPos(-4, -2, 7))
                        .addPos(new BlockPos(-3, -2, -7))
                        .addPos(new BlockPos(-3, -2, 7))
                        .addPos(new BlockPos(-2, -2, -8))
                        .addPos(new BlockPos(-2, -2, -7))
                        .addPos(new BlockPos(-2, -2, 7))
                        .addPos(new BlockPos(-2, -2, 8))
                        .addPos(new BlockPos(-1, -2, -8))
                        .addPos(new BlockPos(-1, -2, 8))
                        .addPos(new BlockPos(0, -2, -8))
                        .addPos(new BlockPos(0, -2, 0))
                        .addPos(new BlockPos(0, -2, 8))
                        .addPos(new BlockPos(1, -2, -8))
                        .addPos(new BlockPos(1, -2, 8))
                        .addPos(new BlockPos(2, -2, -8))
                        .addPos(new BlockPos(2, -2, -7))
                        .addPos(new BlockPos(2, -2, 7))
                        .addPos(new BlockPos(2, -2, 8))
                        .addPos(new BlockPos(3, -2, -7))
                        .addPos(new BlockPos(3, -2, 7))
                        .addPos(new BlockPos(4, -2, -7))
                        .addPos(new BlockPos(4, -2, 7))
                        .addPos(new BlockPos(5, -2, -7))
                        .addPos(new BlockPos(5, -2, -6))
                        .addPos(new BlockPos(5, -2, 6))
                        .addPos(new BlockPos(5, -2, 7))
                        .addPos(new BlockPos(6, -2, -6))
                        .addPos(new BlockPos(6, -2, -5))
                        .addPos(new BlockPos(6, -2, 5))
                        .addPos(new BlockPos(6, -2, 6))
                        .addPos(new BlockPos(7, -2, -5))
                        .addPos(new BlockPos(7, -2, -4))
                        .addPos(new BlockPos(7, -2, -3))
                        .addPos(new BlockPos(7, -2, -2))
                        .addPos(new BlockPos(7, -2, 2))
                        .addPos(new BlockPos(7, -2, 3))
                        .addPos(new BlockPos(7, -2, 4))
                        .addPos(new BlockPos(7, -2, 5))
                        .addPos(new BlockPos(8, -2, -2))
                        .addPos(new BlockPos(8, -2, -1))
                        .addPos(new BlockPos(8, -2, 0))
                        .addPos(new BlockPos(8, -2, 1))
                        .addPos(new BlockPos(8, -2, 2))
                        .addPos(new BlockPos(-6, -1, 0))
                        .addPos(new BlockPos(0, -1, -6))
                        .addPos(new BlockPos(0, -1, 6))
                        .addPos(new BlockPos(6, -1, 0)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.stairs.name, Map.of("half", "top", "waterlogged", "false", "shape", "outer_left", "facing", "south"))
                        .addPos(new BlockPos(-9, -1, -3))
                        .addPos(new BlockPos(-8, -1, -6))
                        .addPos(new BlockPos(4, -1, 5))
                        .addPos(new BlockPos(5, -1, 4))
                        .addPos(new BlockPos(6, -1, 1)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.stairs.name, Map.of("half", "top", "waterlogged", "false", "shape", "straight", "facing", "east"))
                        .addPos(new BlockPos(-9, -1, -2))
                        .addPos(new BlockPos(-9, -1, -1))
                        .addPos(new BlockPos(-9, -1, 0))
                        .addPos(new BlockPos(-9, -1, 1))
                        .addPos(new BlockPos(-9, -1, 2))
                        .addPos(new BlockPos(-8, -1, -5))
                        .addPos(new BlockPos(-8, -1, -4))
                        .addPos(new BlockPos(-8, -1, 4))
                        .addPos(new BlockPos(-8, -1, 5))
                        .addPos(new BlockPos(6, -1, -3))
                        .addPos(new BlockPos(6, -1, -2))
                        .addPos(new BlockPos(6, -1, 2))
                        .addPos(new BlockPos(6, -1, 3))
                        .addPos(new BlockPos(7, -1, 0))
                        .addPos(new BlockPos(-1, 1, 0)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.stairs.name, Map.of("half", "top", "waterlogged", "false", "shape", "outer_right", "facing", "north"))
                        .addPos(new BlockPos(-9, -1, 3))
                        .addPos(new BlockPos(-8, -1, 6))
                        .addPos(new BlockPos(-7, -1, 7))
                        .addPos(new BlockPos(4, -1, -5))
                        .addPos(new BlockPos(5, -1, -4))
                        .addPos(new BlockPos(6, -1, -1)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.stairs.name, Map.of("half", "top", "waterlogged", "false", "shape", "inner_left", "facing", "south"))
                        .addPos(new BlockPos(-8, -1, -3))
                        .addPos(new BlockPos(-7, -1, -6))
                        .addPos(new BlockPos(-6, -1, -7))
                        .addPos(new BlockPos(-3, -1, -8))
                        .addPos(new BlockPos(1, -1, 7)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.stairs.name, Map.of("half", "top", "waterlogged", "false", "shape", "inner_left", "facing", "east"))
                        .addPos(new BlockPos(-8, -1, 3))
                        .addPos(new BlockPos(-7, -1, 6))
                        .addPos(new BlockPos(-6, -1, 7))
                        .addPos(new BlockPos(-3, -1, 8))
                        .addPos(new BlockPos(4, -1, -6))
                        .addPos(new BlockPos(5, -1, -5))
                        .addPos(new BlockPos(6, -1, -4))
                        .addPos(new BlockPos(7, -1, -1)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.stairs.name, Map.of("half", "top", "waterlogged", "false", "shape", "outer_right", "facing", "east"))
                        .addPos(new BlockPos(-7, -1, -7))
                        .addPos(new BlockPos(-6, -1, -8))
                        .addPos(new BlockPos(-3, -1, -9))
                        .addPos(new BlockPos(1, -1, 6)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.stairs.name, Map.of("half", "top", "waterlogged", "false", "shape", "inner_right", "facing", "west"))
                        .addPos(new BlockPos(-7, -1, -1))
                        .addPos(new BlockPos(-5, -1, -5))
                        .addPos(new BlockPos(-4, -1, -6)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.stairs.name, Map.of("half", "top", "waterlogged", "false", "shape", "straight", "facing", "west"))
                        .addPos(new BlockPos(-7, -1, 0))
                        .addPos(new BlockPos(-6, -1, -3))
                        .addPos(new BlockPos(-6, -1, -2))
                        .addPos(new BlockPos(-6, -1, 2))
                        .addPos(new BlockPos(-6, -1, 3))
                        .addPos(new BlockPos(8, -1, -5))
                        .addPos(new BlockPos(8, -1, -4))
                        .addPos(new BlockPos(8, -1, 4))
                        .addPos(new BlockPos(8, -1, 5))
                        .addPos(new BlockPos(9, -1, -2))
                        .addPos(new BlockPos(9, -1, -1))
                        .addPos(new BlockPos(9, -1, 0))
                        .addPos(new BlockPos(9, -1, 1))
                        .addPos(new BlockPos(9, -1, 2))
                        .addPos(new BlockPos(1, 1, 0)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.stairs.name, Map.of("half", "top", "waterlogged", "false", "shape", "inner_left", "facing", "west"))
                        .addPos(new BlockPos(-7, -1, 1))
                        .addPos(new BlockPos(8, -1, -3)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.stairs.name, Map.of("half", "top", "waterlogged", "false", "shape", "inner_left", "facing", "north"))
                        .addPos(new BlockPos(-6, -1, -4))
                        .addPos(new BlockPos(-1, -1, -7))
                        .addPos(new BlockPos(3, -1, 8))
                        .addPos(new BlockPos(6, -1, 7))
                        .addPos(new BlockPos(7, -1, 6))
                        .addPos(new BlockPos(8, -1, 3)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.stairs.name, Map.of("half", "top", "waterlogged", "false", "shape", "outer_left", "facing", "north"))
                        .addPos(new BlockPos(-6, -1, -1))
                        .addPos(new BlockPos(-4, -1, -5))
                        .addPos(new BlockPos(8, -1, 6))
                        .addPos(new BlockPos(9, -1, 3)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.stairs.name, Map.of("half", "top", "waterlogged", "false", "shape", "outer_right", "facing", "south"))
                        .addPos(new BlockPos(-6, -1, 1))
                        .addPos(new BlockPos(9, -1, -3)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.stairs.name, Map.of("half", "top", "waterlogged", "false", "shape", "inner_right", "facing", "south"))
                        .addPos(new BlockPos(-6, -1, 4))
                        .addPos(new BlockPos(-5, -1, 5))
                        .addPos(new BlockPos(-4, -1, 6))
                        .addPos(new BlockPos(-1, -1, 7))
                        .addPos(new BlockPos(3, -1, -8))
                        .addPos(new BlockPos(6, -1, -7))
                        .addPos(new BlockPos(7, -1, -6)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.stairs.name, Map.of("half", "top", "waterlogged", "false", "shape", "outer_left", "facing", "east"))
                        .addPos(new BlockPos(-6, -1, 8))
                        .addPos(new BlockPos(-3, -1, 9))
                        .addPos(new BlockPos(1, -1, -6)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.stairs.name, Map.of("half", "top", "waterlogged", "false", "shape", "straight", "facing", "south"))
                        .addPos(new BlockPos(-5, -1, -8))
                        .addPos(new BlockPos(-4, -1, -8))
                        .addPos(new BlockPos(-3, -1, 6))
                        .addPos(new BlockPos(-2, -1, -9))
                        .addPos(new BlockPos(-2, -1, 6))
                        .addPos(new BlockPos(-1, -1, -9))
                        .addPos(new BlockPos(0, -1, -9))
                        .addPos(new BlockPos(0, -1, 7))
                        .addPos(new BlockPos(1, -1, -9))
                        .addPos(new BlockPos(2, -1, -9))
                        .addPos(new BlockPos(2, -1, 6))
                        .addPos(new BlockPos(3, -1, 6))
                        .addPos(new BlockPos(4, -1, -8))
                        .addPos(new BlockPos(5, -1, -8))
                        .addPos(new BlockPos(0, 1, -1)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.stairs.name, Map.of("half", "top", "waterlogged", "false", "shape", "outer_right", "facing", "west"))
                        .addPos(new BlockPos(-5, -1, -4))
                        .addPos(new BlockPos(-1, -1, -6))
                        .addPos(new BlockPos(3, -1, 9))
                        .addPos(new BlockPos(6, -1, 8))
                        .addPos(new BlockPos(7, -1, 7)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.stairs.name, Map.of("half", "top", "waterlogged", "false", "shape", "outer_left", "facing", "west"))
                        .addPos(new BlockPos(-5, -1, 4))
                        .addPos(new BlockPos(-4, -1, 5))
                        .addPos(new BlockPos(-1, -1, 6))
                        .addPos(new BlockPos(3, -1, -9))
                        .addPos(new BlockPos(6, -1, -8))
                        .addPos(new BlockPos(7, -1, -7))
                        .addPos(new BlockPos(8, -1, -6)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.stairs.name, Map.of("half", "top", "waterlogged", "false", "shape", "straight", "facing", "north"))
                        .addPos(new BlockPos(-5, -1, 8))
                        .addPos(new BlockPos(-4, -1, 8))
                        .addPos(new BlockPos(-3, -1, -6))
                        .addPos(new BlockPos(-2, -1, -6))
                        .addPos(new BlockPos(-2, -1, 9))
                        .addPos(new BlockPos(-1, -1, 9))
                        .addPos(new BlockPos(0, -1, -7))
                        .addPos(new BlockPos(0, -1, 9))
                        .addPos(new BlockPos(1, -1, 9))
                        .addPos(new BlockPos(2, -1, -6))
                        .addPos(new BlockPos(2, -1, 9))
                        .addPos(new BlockPos(3, -1, -6))
                        .addPos(new BlockPos(4, -1, 8))
                        .addPos(new BlockPos(5, -1, 8))
                        .addPos(new BlockPos(0, 1, 1)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.stairs.name, Map.of("half", "bottom", "waterlogged", "false", "shape", "straight", "facing", "east"))
                        .addPos(new BlockPos(-1, -1, 0))
                        .addPos(new BlockPos(-9, 1, -2))
                        .addPos(new BlockPos(-9, 1, -1))
                        .addPos(new BlockPos(-9, 1, 0))
                        .addPos(new BlockPos(-9, 1, 1))
                        .addPos(new BlockPos(-9, 1, 2))
                        .addPos(new BlockPos(-8, 1, -5))
                        .addPos(new BlockPos(-8, 1, -4))
                        .addPos(new BlockPos(-8, 1, 4))
                        .addPos(new BlockPos(-8, 1, 5))
                        .addPos(new BlockPos(6, 1, -3))
                        .addPos(new BlockPos(6, 1, -2))
                        .addPos(new BlockPos(6, 1, 2))
                        .addPos(new BlockPos(6, 1, 3))
                        .addPos(new BlockPos(7, 1, 0)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.stairs.name, Map.of("half", "bottom", "waterlogged", "false", "shape", "straight", "facing", "south"))
                        .addPos(new BlockPos(0, -1, -1))
                        .addPos(new BlockPos(-5, 1, -8))
                        .addPos(new BlockPos(-4, 1, -8))
                        .addPos(new BlockPos(-3, 1, 6))
                        .addPos(new BlockPos(-2, 1, -9))
                        .addPos(new BlockPos(-2, 1, 6))
                        .addPos(new BlockPos(-1, 1, -9))
                        .addPos(new BlockPos(0, 1, -9))
                        .addPos(new BlockPos(0, 1, 7))
                        .addPos(new BlockPos(1, 1, -9))
                        .addPos(new BlockPos(2, 1, -9))
                        .addPos(new BlockPos(2, 1, 6))
                        .addPos(new BlockPos(3, 1, 6))
                        .addPos(new BlockPos(4, 1, -8))
                        .addPos(new BlockPos(5, 1, -8)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.stairs.name, Map.of("half", "bottom", "waterlogged", "false", "shape", "straight", "facing", "north"))
                        .addPos(new BlockPos(0, -1, 1))
                        .addPos(new BlockPos(-5, 1, 8))
                        .addPos(new BlockPos(-4, 1, 8))
                        .addPos(new BlockPos(-3, 1, -6))
                        .addPos(new BlockPos(-2, 1, -6))
                        .addPos(new BlockPos(-2, 1, 9))
                        .addPos(new BlockPos(-1, 1, 9))
                        .addPos(new BlockPos(0, 1, -7))
                        .addPos(new BlockPos(0, 1, 9))
                        .addPos(new BlockPos(1, 1, 9))
                        .addPos(new BlockPos(2, 1, -6))
                        .addPos(new BlockPos(2, 1, 9))
                        .addPos(new BlockPos(3, 1, -6))
                        .addPos(new BlockPos(4, 1, 8))
                        .addPos(new BlockPos(5, 1, 8)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.stairs.name, Map.of("half", "top", "waterlogged", "false", "shape", "inner_right", "facing", "north"))
                        .addPos(new BlockPos(1, -1, -7)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.stairs.name, Map.of("half", "bottom", "waterlogged", "false", "shape", "straight", "facing", "west"))
                        .addPos(new BlockPos(1, -1, 0))
                        .addPos(new BlockPos(-7, 1, 0))
                        .addPos(new BlockPos(-6, 1, -3))
                        .addPos(new BlockPos(-6, 1, -2))
                        .addPos(new BlockPos(-6, 1, 2))
                        .addPos(new BlockPos(-6, 1, 3))
                        .addPos(new BlockPos(8, 1, -5))
                        .addPos(new BlockPos(8, 1, -4))
                        .addPos(new BlockPos(8, 1, 4))
                        .addPos(new BlockPos(8, 1, 5))
                        .addPos(new BlockPos(9, 1, -2))
                        .addPos(new BlockPos(9, 1, -1))
                        .addPos(new BlockPos(9, 1, 0))
                        .addPos(new BlockPos(9, 1, 1))
                        .addPos(new BlockPos(9, 1, 2)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.stairs.name, Map.of("half", "top", "waterlogged", "false", "shape", "inner_right", "facing", "east"))
                        .addPos(new BlockPos(4, -1, 6))
                        .addPos(new BlockPos(5, -1, 5))
                        .addPos(new BlockPos(6, -1, 4))
                        .addPos(new BlockPos(7, -1, 1)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.slab.name, Map.of("half", "true", "waterlogged", "false", "facing", "east"))
                        .addPos(new BlockPos(-10, 0, -2))
                        .addPos(new BlockPos(-10, 0, -1))
                        .addPos(new BlockPos(-10, 0, 0))
                        .addPos(new BlockPos(-10, 0, 1))
                        .addPos(new BlockPos(-10, 0, 2))
                        .addPos(new BlockPos(-9, 0, -5))
                        .addPos(new BlockPos(-9, 0, -4))
                        .addPos(new BlockPos(-9, 0, 4))
                        .addPos(new BlockPos(-9, 0, 5))
                        .addPos(new BlockPos(5, 0, -3))
                        .addPos(new BlockPos(5, 0, -2))
                        .addPos(new BlockPos(5, 0, 2))
                        .addPos(new BlockPos(5, 0, 3)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.slab.name, Map.of("half", "true", "waterlogged", "false", "facing", "south"))
                        .addPos(new BlockPos(-5, 0, -9))
                        .addPos(new BlockPos(-4, 0, -9))
                        .addPos(new BlockPos(-3, 0, 5))
                        .addPos(new BlockPos(-2, 0, -10))
                        .addPos(new BlockPos(-2, 0, 5))
                        .addPos(new BlockPos(-1, 0, -10))
                        .addPos(new BlockPos(0, 0, -10))
                        .addPos(new BlockPos(1, 0, -10))
                        .addPos(new BlockPos(2, 0, -10))
                        .addPos(new BlockPos(2, 0, 5))
                        .addPos(new BlockPos(3, 0, 5))
                        .addPos(new BlockPos(4, 0, -9))
                        .addPos(new BlockPos(5, 0, -9)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.slab.name, Map.of("half", "true", "waterlogged", "false", "facing", "west"))
                        .addPos(new BlockPos(-5, 0, -3))
                        .addPos(new BlockPos(-5, 0, -2))
                        .addPos(new BlockPos(-5, 0, 2))
                        .addPos(new BlockPos(-5, 0, 3))
                        .addPos(new BlockPos(9, 0, -5))
                        .addPos(new BlockPos(9, 0, -4))
                        .addPos(new BlockPos(9, 0, 4))
                        .addPos(new BlockPos(9, 0, 5))
                        .addPos(new BlockPos(10, 0, -2))
                        .addPos(new BlockPos(10, 0, -1))
                        .addPos(new BlockPos(10, 0, 0))
                        .addPos(new BlockPos(10, 0, 1))
                        .addPos(new BlockPos(10, 0, 2)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.slab.name, Map.of("half", "true", "waterlogged", "false", "facing", "north"))
                        .addPos(new BlockPos(-5, 0, 9))
                        .addPos(new BlockPos(-4, 0, 9))
                        .addPos(new BlockPos(-3, 0, -5))
                        .addPos(new BlockPos(-2, 0, -5))
                        .addPos(new BlockPos(-2, 0, 10))
                        .addPos(new BlockPos(-1, 0, 10))
                        .addPos(new BlockPos(0, 0, 10))
                        .addPos(new BlockPos(1, 0, 10))
                        .addPos(new BlockPos(2, 0, -5))
                        .addPos(new BlockPos(2, 0, 10))
                        .addPos(new BlockPos(3, 0, -5))
                        .addPos(new BlockPos(4, 0, 9))
                        .addPos(new BlockPos(5, 0, 9)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.stairs.name, Map.of("half", "bottom", "waterlogged", "false", "shape", "outer_left", "facing", "south"))
                        .addPos(new BlockPos(-9, 1, -3))
                        .addPos(new BlockPos(-8, 1, -6))
                        .addPos(new BlockPos(-7, 1, -7))
                        .addPos(new BlockPos(-3, 1, -9))
                        .addPos(new BlockPos(1, 1, 6))
                        .addPos(new BlockPos(4, 1, 5))
                        .addPos(new BlockPos(5, 1, 4))
                        .addPos(new BlockPos(6, 1, 1)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.stairs.name, Map.of("half", "bottom", "waterlogged", "false", "shape", "outer_left", "facing", "east"))
                        .addPos(new BlockPos(-9, 1, 3))
                        .addPos(new BlockPos(-7, 1, 7))
                        .addPos(new BlockPos(-6, 1, 8))
                        .addPos(new BlockPos(-3, 1, 9))
                        .addPos(new BlockPos(1, 1, -6))
                        .addPos(new BlockPos(4, 1, -5))
                        .addPos(new BlockPos(5, 1, -4))
                        .addPos(new BlockPos(6, 1, -1)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.stairs.name, Map.of("half", "bottom", "waterlogged", "false", "shape", "inner_right", "facing", "east"))
                        .addPos(new BlockPos(-8, 1, -3))
                        .addPos(new BlockPos(-7, 1, -6))
                        .addPos(new BlockPos(-6, 1, -7))
                        .addPos(new BlockPos(-3, 1, -8))
                        .addPos(new BlockPos(1, 1, 7))
                        .addPos(new BlockPos(4, 1, 6))
                        .addPos(new BlockPos(5, 1, 5))
                        .addPos(new BlockPos(6, 1, 4))
                        .addPos(new BlockPos(7, 1, 1)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.stairs.name, Map.of("half", "bottom", "waterlogged", "false", "shape", "inner_right", "facing", "north"))
                        .addPos(new BlockPos(-8, 1, 3))
                        .addPos(new BlockPos(-7, 1, 6))
                        .addPos(new BlockPos(-6, 1, 7))
                        .addPos(new BlockPos(-3, 1, 8))
                        .addPos(new BlockPos(1, 1, -7))
                        .addPos(new BlockPos(4, 1, -6))
                        .addPos(new BlockPos(5, 1, -5))
                        .addPos(new BlockPos(6, 1, -4))
                        .addPos(new BlockPos(7, 1, -1)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.stairs.name, Map.of("half", "bottom", "waterlogged", "false", "shape", "outer_right", "facing", "north"))
                        .addPos(new BlockPos(-8, 1, 6)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.stairs.name, Map.of("half", "bottom", "waterlogged", "false", "shape", "inner_right", "facing", "west"))
                        .addPos(new BlockPos(-7, 1, -1))
                        .addPos(new BlockPos(-6, 1, -4))
                        .addPos(new BlockPos(-5, 1, -5))
                        .addPos(new BlockPos(-4, 1, -6))
                        .addPos(new BlockPos(-1, 1, -7))
                        .addPos(new BlockPos(3, 1, 8))
                        .addPos(new BlockPos(6, 1, 7))
                        .addPos(new BlockPos(7, 1, 6))
                        .addPos(new BlockPos(8, 1, 3)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.stairs.name, Map.of("half", "bottom", "waterlogged", "false", "shape", "inner_left", "facing", "west"))
                        .addPos(new BlockPos(-7, 1, 1)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.stairs.name, Map.of("half", "bottom", "waterlogged", "false", "shape", "outer_right", "facing", "east"))
                        .addPos(new BlockPos(-6, 1, -8)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.stairs.name, Map.of("half", "bottom", "waterlogged", "false", "shape", "outer_left", "facing", "north"))
                        .addPos(new BlockPos(-6, 1, -1))
                        .addPos(new BlockPos(-5, 1, -4))
                        .addPos(new BlockPos(-4, 1, -5))
                        .addPos(new BlockPos(-1, 1, -6))
                        .addPos(new BlockPos(3, 1, 9))
                        .addPos(new BlockPos(7, 1, 7))
                        .addPos(new BlockPos(8, 1, 6))
                        .addPos(new BlockPos(9, 1, 3)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.slab.name, Map.of("half", "true", "waterlogged", "false", "facing", "down"))
                        .addPos(new BlockPos(-6, 1, 0))
                        .addPos(new BlockPos(0, 1, -6))
                        .addPos(new BlockPos(0, 1, 6))
                        .addPos(new BlockPos(6, 1, 0))
                        .addPos(new BlockPos(-8, 2, -2))
                        .addPos(new BlockPos(-8, 2, -1))
                        .addPos(new BlockPos(-8, 2, 0))
                        .addPos(new BlockPos(-8, 2, 1))
                        .addPos(new BlockPos(-8, 2, 2))
                        .addPos(new BlockPos(-7, 2, -5))
                        .addPos(new BlockPos(-7, 2, -4))
                        .addPos(new BlockPos(-7, 2, -3))
                        .addPos(new BlockPos(-7, 2, -2))
                        .addPos(new BlockPos(-7, 2, 2))
                        .addPos(new BlockPos(-7, 2, 3))
                        .addPos(new BlockPos(-7, 2, 4))
                        .addPos(new BlockPos(-7, 2, 5))
                        .addPos(new BlockPos(-6, 2, -6))
                        .addPos(new BlockPos(-6, 2, -5))
                        .addPos(new BlockPos(-6, 2, 5))
                        .addPos(new BlockPos(-6, 2, 6))
                        .addPos(new BlockPos(-5, 2, -7))
                        .addPos(new BlockPos(-5, 2, -6))
                        .addPos(new BlockPos(-5, 2, 6))
                        .addPos(new BlockPos(-5, 2, 7))
                        .addPos(new BlockPos(-4, 2, -7))
                        .addPos(new BlockPos(-4, 2, 7))
                        .addPos(new BlockPos(-3, 2, -7))
                        .addPos(new BlockPos(-3, 2, 7))
                        .addPos(new BlockPos(-2, 2, -8))
                        .addPos(new BlockPos(-2, 2, -7))
                        .addPos(new BlockPos(-2, 2, 7))
                        .addPos(new BlockPos(-2, 2, 8))
                        .addPos(new BlockPos(-1, 2, -8))
                        .addPos(new BlockPos(-1, 2, 8))
                        .addPos(new BlockPos(0, 2, -8))
                        .addPos(new BlockPos(0, 2, 0))
                        .addPos(new BlockPos(0, 2, 8))
                        .addPos(new BlockPos(1, 2, -8))
                        .addPos(new BlockPos(1, 2, 8))
                        .addPos(new BlockPos(2, 2, -8))
                        .addPos(new BlockPos(2, 2, -7))
                        .addPos(new BlockPos(2, 2, 7))
                        .addPos(new BlockPos(2, 2, 8))
                        .addPos(new BlockPos(3, 2, -7))
                        .addPos(new BlockPos(3, 2, 7))
                        .addPos(new BlockPos(4, 2, -7))
                        .addPos(new BlockPos(4, 2, 7))
                        .addPos(new BlockPos(5, 2, -7))
                        .addPos(new BlockPos(5, 2, -6))
                        .addPos(new BlockPos(5, 2, 6))
                        .addPos(new BlockPos(5, 2, 7))
                        .addPos(new BlockPos(6, 2, -6))
                        .addPos(new BlockPos(6, 2, -5))
                        .addPos(new BlockPos(6, 2, 5))
                        .addPos(new BlockPos(6, 2, 6))
                        .addPos(new BlockPos(7, 2, -5))
                        .addPos(new BlockPos(7, 2, -4))
                        .addPos(new BlockPos(7, 2, -3))
                        .addPos(new BlockPos(7, 2, -2))
                        .addPos(new BlockPos(7, 2, 2))
                        .addPos(new BlockPos(7, 2, 3))
                        .addPos(new BlockPos(7, 2, 4))
                        .addPos(new BlockPos(7, 2, 5))
                        .addPos(new BlockPos(8, 2, -2))
                        .addPos(new BlockPos(8, 2, -1))
                        .addPos(new BlockPos(8, 2, 0))
                        .addPos(new BlockPos(8, 2, 1))
                        .addPos(new BlockPos(8, 2, 2)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.stairs.name, Map.of("half", "bottom", "waterlogged", "false", "shape", "outer_right", "facing", "south"))
                        .addPos(new BlockPos(-6, 1, 1))
                        .addPos(new BlockPos(8, 1, -6)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.stairs.name, Map.of("half", "bottom", "waterlogged", "false", "shape", "inner_right", "facing", "south"))
                        .addPos(new BlockPos(-6, 1, 4))
                        .addPos(new BlockPos(-5, 1, 5))
                        .addPos(new BlockPos(-4, 1, 6))
                        .addPos(new BlockPos(-1, 1, 7))
                        .addPos(new BlockPos(3, 1, -8))
                        .addPos(new BlockPos(6, 1, -7))
                        .addPos(new BlockPos(7, 1, -6))
                        .addPos(new BlockPos(8, 1, -3)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.stairs.name, Map.of("half", "bottom", "waterlogged", "false", "shape", "outer_left", "facing", "west"))
                        .addPos(new BlockPos(-5, 1, 4))
                        .addPos(new BlockPos(-4, 1, 5))
                        .addPos(new BlockPos(-1, 1, 6))
                        .addPos(new BlockPos(3, 1, -9))
                        .addPos(new BlockPos(6, 1, -8))
                        .addPos(new BlockPos(7, 1, -7))
                        .addPos(new BlockPos(9, 1, -3)),
                new IMultiBlockPack.ManaLevelAcceptableBlockPack(OreBlock.stairs.name, Map.of("half", "bottom", "waterlogged", "false", "shape", "outer_right", "facing", "west"))
                        .addPos(new BlockPos(6, 1, 8)),
                new IMultiBlockPack.BlockStateBlockPack<ManaLevel>(() -> BlockStateUtil.create(ForgeRegistries.BLOCKS.getValue(new ResourceLocation("minecraft:beacon")), (Map<String, String>) null))
                        .addPos(new BlockPos(-6, 0, 0))
                        .addPos(new BlockPos(0, 0, -6))
                        .addPos(new BlockPos(0, 0, 6))
                        .addPos(new BlockPos(6, 0, 0)));
    }
}
